# Generated by cpp11: do not edit by hand

dust_m4_capabilities <- function() {
  .Call(`_monkeyspam_dust_m4_capabilities`)
}

dust_m4_gpu_info <- function() {
  .Call(`_monkeyspam_dust_m4_gpu_info`)
}

dust_cpu_m4_alloc <- function(r_pars, pars_multi, time, r_n_particles, n_threads, r_seed, deterministic, gpu_config) {
  .Call(`_monkeyspam_dust_cpu_m4_alloc`, r_pars, pars_multi, time, r_n_particles, n_threads, r_seed, deterministic, gpu_config)
}

dust_cpu_m4_run <- function(ptr, time_end) {
  .Call(`_monkeyspam_dust_cpu_m4_run`, ptr, time_end)
}

dust_cpu_m4_simulate <- function(ptr, time_end) {
  .Call(`_monkeyspam_dust_cpu_m4_simulate`, ptr, time_end)
}

dust_cpu_m4_set_index <- function(ptr, r_index) {
  .Call(`_monkeyspam_dust_cpu_m4_set_index`, ptr, r_index)
}

dust_cpu_m4_update_state <- function(ptr, r_pars, r_state, r_time, r_set_initial_state) {
  .Call(`_monkeyspam_dust_cpu_m4_update_state`, ptr, r_pars, r_state, r_time, r_set_initial_state)
}

dust_cpu_m4_state <- function(ptr, r_index) {
  .Call(`_monkeyspam_dust_cpu_m4_state`, ptr, r_index)
}

dust_cpu_m4_time <- function(ptr) {
  .Call(`_monkeyspam_dust_cpu_m4_time`, ptr)
}

dust_cpu_m4_reorder <- function(ptr, r_index) {
  invisible(.Call(`_monkeyspam_dust_cpu_m4_reorder`, ptr, r_index))
}

dust_cpu_m4_resample <- function(ptr, r_weights) {
  .Call(`_monkeyspam_dust_cpu_m4_resample`, ptr, r_weights)
}

dust_cpu_m4_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_monkeyspam_dust_cpu_m4_rng_state`, ptr, first_only, last_only)
}

dust_cpu_m4_set_rng_state <- function(ptr, rng_state) {
  .Call(`_monkeyspam_dust_cpu_m4_set_rng_state`, ptr, rng_state)
}

dust_cpu_m4_set_data <- function(ptr, data, shared) {
  .Call(`_monkeyspam_dust_cpu_m4_set_data`, ptr, data, shared)
}

dust_cpu_m4_compare_data <- function(ptr) {
  .Call(`_monkeyspam_dust_cpu_m4_compare_data`, ptr)
}

dust_cpu_m4_filter <- function(ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood) {
  .Call(`_monkeyspam_dust_cpu_m4_filter`, ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood)
}

dust_cpu_m4_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_monkeyspam_dust_cpu_m4_set_n_threads`, ptr, n_threads))
}

dust_cpu_m4_n_state <- function(ptr) {
  .Call(`_monkeyspam_dust_cpu_m4_n_state`, ptr)
}
